#!/usr/bin/env python3
"""Build the print-and-play PDF of playtest placeholder cards.

Lays every placeholder card out on US Letter pages (nine cards per page,
2.5in x 3.5in, with cut borders) and writes
assets/playtest/cavendish-cards-playtest.pdf.

Card faces are generated by scripts/build-placeholders.py (with the
illustrations from scripts/card-art.py), which this script reuses — so the PDF
always matches the placeholder SVGs. Interaction cards are
skipped (they already have finished faces).

Unlike build-placeholders.py, this needs two libraries:
    pip install cairosvg weasyprint

WeasyPrint also needs system libraries (Pango, cairo, GDK-PixBuf); see
https://doc.courtbouillon.org/weasyprint/stable/first_steps.html

This PDF is not reproducible: three consecutive builds from identical inputs
produce three different files, differing by a few bytes with identical page
content. (The card PNGs are written to a random temp directory whose file://
paths go into the HTML WeasyPrint renders; SOURCE_DATE_EPOCH does not fix it,
so it is not the PDF timestamp.) Left alone, that means every build-all.py run
leaves a 3.7MB binary dirty in git whether or not anything changed -- noise
that hides real staleness and bloats history if committed.

So the build is skipped when its inputs have not moved. A hash of the card
files, the three scripts that shape the output, and the rendering library
versions is kept in a sidecar next to the PDF; a mismatch rebuilds, a match
does nothing. Pass --force to rebuild regardless.

Usage, from the repo root:
    python3 scripts/build-playtest-pdf.py [output.pdf] [--force]
"""

from pathlib import Path
import hashlib
import importlib.util
import sys
import tempfile


def _inputs_digest(root, versions):
    """Hash everything that changes this PDF's content.

    Covers the cards, build-placeholders.py and card-art.py (which draw the
    faces) and this script (which lays them out), plus the rendering library
    versions, so a toolchain upgrade rebuilds too. It does NOT cover system fonts -- cairosvg
    rasterizes text with whatever is installed, so a font change will not
    trigger a rebuild. Use --force after one.
    """
    h = hashlib.sha256()
    for card in sorted((root / "cards").rglob("*.md")):
        h.update(str(card.relative_to(root)).encode("utf-8"))
        h.update(card.read_bytes())
    for script in ("build-placeholders.py", "card-art.py",
                   "build-playtest-pdf.py"):
        h.update((root / "scripts" / script).read_bytes())
    for name, version in sorted(versions.items()):
        h.update(f"{name}={version}".encode("utf-8"))
    return h.hexdigest()


def _load_placeholders():
    """Load the sibling build-placeholders.py module (hyphenated filename)."""
    path = Path(__file__).resolve().parent / "build-placeholders.py"
    if not path.exists():
        sys.exit(f"Could not find {path}")
    spec = importlib.util.spec_from_file_location("build_placeholders", path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def main():
    try:
        import cairosvg
        import weasyprint
    except ImportError as exc:
        sys.exit(
            f"Missing dependency: {exc.name}.\n"
            "This script needs cairosvg and weasyprint:\n"
            "    pip install cairosvg weasyprint\n"
            "WeasyPrint also needs system libraries (Pango, cairo, GDK-PixBuf); see\n"
            "https://doc.courtbouillon.org/weasyprint/stable/first_steps.html"
        )

    bp = _load_placeholders()
    root = Path(__file__).resolve().parent.parent
    cards_dir = root / "cards"
    if not cards_dir.is_dir():
        sys.exit(f"cards/ not found at {cards_dir}")

    args = [a for a in sys.argv[1:] if not a.startswith("-")]
    force = "--force" in sys.argv[1:]
    out_path = (Path(args[0]).resolve() if args
                else root / "assets" / "playtest" / "cavendish-cards-playtest.pdf")
    stamp_path = out_path.with_suffix(".inputs.sha256")

    digest = _inputs_digest(root, {"cairosvg": cairosvg.__version__,
                                   "weasyprint": weasyprint.__version__})
    if not force and out_path.exists() and stamp_path.exists():
        if stamp_path.read_text(encoding="utf-8").strip() == digest:
            print(f"{out_path.name} is up to date (inputs unchanged); skipping. "
                  f"Use --force to rebuild.")
            return

    tmp = tempfile.TemporaryDirectory()
    png_paths = []
    total = 0
    for family in bp.ORDER:
        for card in sorted((cards_dir / family).glob("*.md")):
            name, sections = bp.parse_card(card)
            if not name:
                continue
            svg = bp.build_svg(
                family, card.stem, name,
                sections.get("Image cue", "").strip(),
                sections.get("Prompt", "").strip(),
            )
            png = Path(tmp.name) / f"{family}__{card.stem}.png"
            cairosvg.svg2png(bytestring=svg.encode("utf-8"), write_to=str(png),
                             output_width=750, output_height=1050)
            png_paths.append(png)
            total += 1

    if not total:
        sys.exit("No cards found to render.")

    cards_html = "".join(
        f'<div class="card"><img src="file://{p}"/></div>' for p in png_paths
    )
    doc = f'''<!DOCTYPE html><html><head><meta charset="utf-8"><style>
@page {{ size: Letter; margin: 0.25in 0.5in;
  @bottom-center {{ content: "Cavendish Cards \u00b7 playtest placeholders \u00b7 not final art";
    font-family: {bp.FONT}; font-size: 7pt; color: #93a1a1; }} }}
html,body {{ margin: 0; padding: 0; }}
.grid {{ width: 7.5in; font-size: 0; }}
.card {{ display: inline-block; width: 2.5in; height: 3.5in; box-sizing: border-box;
  border: 0.4pt solid #cfc8b8; vertical-align: top; overflow: hidden; break-inside: avoid; }}
.card img {{ width: 100%; height: 100%; display: block; }}
</style></head><body><div class="grid">{cards_html}</div></body></html>'''

    weasyprint.HTML(string=doc, base_url=str(root)).write_pdf(str(out_path))
    tmp.cleanup()
    stamp_path.write_text(digest + "\n", encoding="utf-8")
    print(f"Wrote {out_path.name} — {total} cards, {(total + 8) // 9} page(s)")


if __name__ == "__main__":
    main()
