#!/usr/bin/env python3
"""Assemble the Cavendish Cards guidebook from the card files.

Walks cards/<family>/*.md, reads each card's name, image cue, prompt, and
Notes, and writes cavendish-cards-guidebook.md, grouped by family in deck
order (cards alphabetical within each family).

The guidebook is generated. Do not edit it by hand — edit the cards in
cards/ and run this script again.

Usage:
    python3 scripts/build-guidebook.py
"""

from pathlib import Path
import sys

# Family order (deck order) with display name and one-line intro.
FAMILIES = [
    ("places", "Places",
     "The five Cavendish zones. Everything else sits in one of these."),
    ("weather", "Weather",
     "Inner weather, not clinical states — the whole range, good and hard alike."),
    ("what-helps", "What helps",
     "The niche-construction pieces: the ways we change the environment so it fits."),
    ("lily-pad", "Lily pads",
     "The in-between. Every card is a landing place, not a failure."),
    ("grower", "Growers",
     "Who am I today. A non-deficit way to hold that different people bloom in "
     "different conditions."),
    ("love-locution", "Love Locutions",
     "Affirmations. Given between people, never earned — a gift, never a reward."),
    ("interaction", "Interaction",
     "How open I am to talking, right now. The Autistic community's color "
     "communication badges."),
    ("blank", "Blank",
     "The card the deck doesn't have yet. Find the gap, draw it, send it in."),
]

REALM_NOTES = {
    "love-locution":
        "**Penguin pebbling.** Giving someone a Love Locution is *penguin "
        "pebbling* — penguins bring each other pebbles, and these cards are "
        "pebbles you can hand to a person. On paper, the cards are made to be "
        "given this way. In the web app they work the other way round, too: "
        "truths a person claims and turns up for themselves.",
}


def parse_card(path):
    """Return (name, {section_heading: text}) for a card file, excluding License."""
    name = None
    sections = {}
    current = None
    buf = []

    def flush():
        if current is not None:
            sections[current] = "\n".join(buf).strip()

    for line in path.read_text(encoding="utf-8").splitlines():
        if name is None and line.startswith("# ") and not line.startswith("## "):
            name = line[2:].strip()
            continue
        if line.strip() == "----":       # separator before License — stop here
            flush()
            current = None
            buf = []
            break
        if line.startswith("## "):
            flush()
            current = line[3:].strip()
            buf = []
            continue
        if current is not None:
            buf.append(line)
    flush()
    return name, sections


def render_card(name, cue, prompt, notes):
    meta = f"*{cue}*" if cue else ""
    if prompt and prompt != "—":
        meta += f' · "{prompt}"' if meta else f'"{prompt}"'
    elif prompt == "—":
        meta += " · given, not read" if meta else "given, not read"
    parts = [f"### {name}"]
    if meta:
        parts.append(meta)
    parts.append("")
    parts.append(notes if notes else "_No guidebook entry yet._")
    return "\n".join(parts)


def main():
    root = Path(__file__).resolve().parent.parent
    cards_dir = root / "cards"
    out_path = root / "cavendish-cards-guidebook.md"
    if not cards_dir.is_dir():
        sys.exit(f"cards/ not found at {cards_dir}")

    doc = [
        "# Cavendish Cards — Guidebook",
        "",
        "A companion to the deck: what each card means, how to hold it, and where "
        "its metaphor comes from. Like an oracle deck's guidebook — but it "
        "describes the card, never the child.",
        "",
        "_Generated from the card files in `cards/` by "
        "`scripts/build-guidebook.py`. Do not edit this file by hand — edit the "
        "cards and regenerate._",
        "",
    ]

    total = 0
    summary = []
    for slug, display, intro in FAMILIES:
        files = sorted((cards_dir / slug).glob("*.md"))
        if not files:
            continue
        doc += ["----", "", f"## {display}", "", f"_{intro}_", ""]
        if slug in REALM_NOTES:
            doc += [REALM_NOTES[slug], ""]
        count = 0
        for f in files:
            name, sections = parse_card(f)
            if not name:
                print(f"  ! skipped {f} (no card name)", file=sys.stderr)
                continue
            doc.append(render_card(
                name,
                sections.get("Image cue", "").strip(),
                sections.get("Prompt", "").strip(),
                sections.get("Notes", "").strip(),
            ))
            doc.append("")
            count += 1
            total += 1
        summary.append((display, count))

    doc += [
        "----",
        "",
        "Dedicated to the public domain under "
        "[CC0 1.0](https://creativecommons.org/publicdomain/zero/1.0/). "
        "Home: https://stimpunks.org/projects/cavendish-space-project/",
        "",
    ]

    out_path.write_text("\n".join(doc), encoding="utf-8")
    print(f"Wrote {out_path.name} — {total} cards across {len(summary)} families")
    for display, count in summary:
        print(f"  {display}: {count}")


if __name__ == "__main__":
    main()
